[".config/rio/themes"]
type = "archive"
url = "https://github.com/rose-pine/rio-terminal/archive/refs/heads/main.tar.gz"
stripComponents = 1
refreshPeriod = "168h"

[".config/btop/themes"]
type = "archive"
url = "https://github.com/rose-pine/btop/archive/refs/heads/main.tar.gz"
stripComponents = 1
refreshPeriod = "168h"

[".config/alacritty"]
type = "archive"
url = "https://github.com/rose-pine/alacritty/archive/refs/heads/main.tar.gz"
stripComponents = 2
include = [ "*/dist/**" ]
refreshPeriod = "168h"

[".config/bat/themes"]
type = "archive"
url = "https://github.com/drluckyspin/rose-pine-bat/archive/refs/heads/main.tar.gz"
stripComponents = 2
include = [ "*/themes/**" ]
refreshPeriod = "168h"

[".config/silicon"]
type = "archive"
url = "https://github.com/drluckyspin/rose-pine-bat/archive/refs/heads/main.tar.gz"
stripComponents = 2
include = [ "*/themes/**" ]
refreshPeriod = "168h"

[".config/Vencord/themes"]
type = "archive"
url = "https://github.com/rose-pine/discord/archive/refs/heads/main.tar.gz"
stripComponents = 2
include = [ "*/dist/**" ]
refreshPeriod = "168h"


[".config/atuin/themes"]
type = "archive"
url = "https://github.com/rose-pine/atuin/archive/refs/heads/main.tar.gz"
stripComponents = 2
include = [ "*/dist/**" ]
refreshPeriod = "168h"

[".local/share/themes/rose-pine-gtk"]
type = "archive"
url = "https://github.com/rose-pine/gtk/releases/download/v2.2.0/gtk3.tar.gz"
stripComponents = 2
include = [ "gtk3/rose-pine-gtk/**" ]
refreshPeriod = "168h"

[".config/gtk-4.0/rose-pine"]
type = "archive"
url = "https://github.com/rose-pine/gtk/releases/download/v2.2.0/gtk4.tar.gz"
stripComponents = 1
include = [ "gtk4/rose-pine.css" ]
refreshPeriod = "168h"
