stream.rules = [
  {
    matches = [
      {
        application.process.binary = "spotify"
        media.class = "Stream/Output/Audio"
      }
    ]

    actions = {
      update-props = {
        application.id = "spotify"
        media.name = "Spotify"
        state.restore-props = true
      }
    }
  }
]
