# AUTOMATICALLY GENERATED by https://github.com/tqdm/shtab
# Usage:
# 1) Copy this to ~/.config/fish/completions/trash.fish
# 2) Ensure a binary named trash is in your PATH
# See also: https://fishshell.com/docs/current/completions.html#where-to-put-completions


# Parse current commandline:
# - _shtab_trash_cmdpath=(sub)command path seen so far
# - _shtab_trash_npos=number of positional arguments given after it
# - options are skipped based on _shtab_trash_opts_with_value & _shtab_trash_commands lists
function _shtab_trash_scan
  set -g _shtab_trash_cmdpath ''
  set -g _shtab_trash_npos 0
  set -l tokens (commandline -opc)
  set -e tokens[1]
  set -l expect_value 0
  for t in $tokens
    if test $expect_value -eq 1
      set expect_value 0
      continue
    end
    switch "$t"
      case '--*=*'
        continue
      case '-*'
        if contains -- $t $_shtab_trash_opts_with_value
          set expect_value 1
        end
        continue
      case '*'
        if test $_shtab_trash_npos -eq 0
          set -l candidate $t
          if test -n "$_shtab_trash_cmdpath"
            set candidate "$_shtab_trash_cmdpath $t"
          end
          if contains -- $candidate $_shtab_trash_commands
            set -g _shtab_trash_cmdpath $candidate
            continue
          end
        end
        set -g _shtab_trash_npos (math $_shtab_trash_npos + 1)
    end
  end
end

# Condition helper: true if the current (sub)command path equals the given one.
function _shtab_trash_using
  _shtab_trash_scan
  test "$_shtab_trash_cmdpath" = "$argv"
end

set -g _shtab_trash_commands 
set -g _shtab_trash_opts_with_value --print-completion --trash-dir

complete -c trash -e
complete -c trash -f

complete -c trash -n _shtab_trash_using -s h -l help -d 'show this help message and exit'
complete -c trash -n _shtab_trash_using -l print-completion -xka "bash zsh tcsh fish" -d 'print shell completion script'
complete -c trash -n _shtab_trash_using -s d -l directory -d 'ignored (for GNU rm compatibility)'
complete -c trash -n _shtab_trash_using -s f -l force -d 'silently ignore nonexistent files'
complete -c trash -n _shtab_trash_using -s i -l interactive -d 'prompt before every removal'
complete -c trash -n _shtab_trash_using -s r -s R -l recursive -d 'ignored (for GNU rm compatibility)'
complete -c trash -n _shtab_trash_using -l trash-dir -xka "(__fish_complete_directories)" -d 'use TRASHDIR as trash folder'
complete -c trash -n _shtab_trash_using -s v -l verbose -d 'explain what is being done'
complete -c trash -n _shtab_trash_using -l version -d 'show program'"'"'s version number and exit'
complete -c trash -n '_shtab_trash_using; and test $_shtab_trash_npos -ge 0' -ka "(__fish_complete_path (commandline -ct))" -d files

