packages = [ "wayland" ]

[variables]
dpi = "96"
font_size = "14"
terminal = "rio"
browser = "floorp"
waybar_font_size = "12px"

[files]
"config/niri/config-desktop.kdl" = "~/.config/niri/config.kdl"
